[tool.poetry]
name = "cookiecutter-python-mini"
version = "0.1.0"
description = ""
authors = ["Andreas Maier <andreas.maier@ypog.law>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
